# Generated by Django 3.1.7 on 2023-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
    ]
