# Generated by Django 3.1.7 on 2023-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0002_excursion_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='image',
            field=models.ImageField(upload_to='panorama/templates/panorama'),
        ),
    ]
