# Generated by Django 4.1.2 on 2023-02-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
        ('panorama', '0004_alter_excursion_options_alter_panorama_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panorama.excursion'),
        ),
    ]
