# Generated by Django 4.1.2 on 2023-02-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0005_excursion_users_alter_panorama_excursion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='users',
        ),
        migrations.AlterField(
            model_name='panorama',
            name='excursion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panorama.excursion'),
        ),
    ]
