# Generated by Django 4.1.2 on 2023-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0007_excursion_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='image',
            field=models.ImageField(default='notfound.jpg', upload_to=''),
        ),
    ]
