# Generated by Django 4.1.2 on 2023-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0009_remove_excursion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='image',
            field=models.ImageField(default='notfound.jpg', upload_to=''),
        ),
    ]
