# Generated by Django 4.1.2 on 2023-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0010_excursion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=models.ImageField(default='notfound.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='is_private',
            field=models.BooleanField(default=1),
        ),
    ]
