# Generated by Django 4.1.2 on 2023-02-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0011_alter_excursion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=models.ImageField(blank=True, default='notfound.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
