# Generated by Django 4.1.2 on 2023-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0012_alter_excursion_image_alter_panorama_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
