# Generated by Django 4.1.2 on 2023-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0013_alter_panorama_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='description',
        ),
    ]
